# Generated by Django 4.1.3 on 2023-07-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_followers_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('superadmin', 'SUPERADMIN'), ('user', 'USER')], default='user', max_length=50),
        ),
    ]
