# Generated by Django 4.1.3 on 2023-08-19 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
