# Generated by Django 4.1.3 on 2024-05-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_dob_user_gender_user_location_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weblink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
