apiVersion: apps/v1
kind: Deployment
metadata:
  name: weedoc-deploymet
  labels:
    app: weedoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weedoc
  template:
    metadata:
      labels:
        app: weedoc
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8000
