# Generated by Django 4.1.3 on 2023-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
