# Generated by Django 4.1.3 on 2023-08-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_status_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
