# Generated by Django 4.2.2 on 2023-06-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('malayalam', 'MALAYALAM'), ('english', 'ENGLISH'), ('tamil', 'TAMIL'), ('hindi', 'HINDI')], default='malayalam', max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('video', models.URLField()),
                ('genere', models.CharField(choices=[('COMEDY', 'comedy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('HORROR', 'horror')], default='english', max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
