# Generated by Django 4.1.3 on 2023-06-21 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('malayalam', 'MALAYALAM'), ('english', 'ENGLISH'), ('tamil', 'TAMIL'), ('hindi', 'HINDI')], default='malayalam', max_length=200)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('video', models.CharField(blank=True, max_length=500)),
                ('genere', models.CharField(choices=[('COMEDY', 'comedy'), ('ACTION', 'action'), ('DRAMA', 'drama'), ('HORROR', 'horror')], default='comedy', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
