# Generated by Django 4.1.3 on 2023-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genere',
            field=models.CharField(choices=[('comedy', 'COMEDY'), ('action', 'ACTION'), ('drama', 'DRAMA'), ('horror', 'HORROR')], default='comedy', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('malayalam', 'MALAYALAM'), ('english', 'ENGLISH'), ('tamil', 'TAMIL'), ('hindi', 'HINDI')], default='malayalam', max_length=200),
        ),
    ]
