# Generated by Django 4.1.3 on 2023-06-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
