# Generated by Django 4.1.3 on 2023-06-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_ade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ade',
            new_name='age',
        ),
    ]
