# Generated by Django 4.1.3 on 2023-06-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.genere'),
        ),
    ]
