# Generated by Django 4.1.3 on 2023-06-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_genere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genere',
        ),
        migrations.AddField(
            model_name='product',
            name='genere',
            field=models.ManyToManyField(to='products.genere'),
        ),
    ]
