# Generated by Django 4.1.3 on 2023-07-12 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_remove_product_genere_product_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
