# Generated by Django 4.1.3 on 2023-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('pending', 'PENDING')], default='pending', max_length=50),
        ),
    ]
