# Generated by Django 4.1.3 on 2023-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_savedmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_reason',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
