# Generated by Django 4.1.3 on 2024-05-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='languages',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='products.languages'),
            preserve_default=False,
        ),
    ]
