# Generated by Django 4.1.3 on 2024-08-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_prefferedlanguages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='viewscount',
            constraint=models.UniqueConstraint(fields=('product_id',), name='views_constraint'),
        ),
    ]
